// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VijayAnand.WinUITemplates
{
    internal sealed partial class Vsix
    {
        public const string Id = "WinUITemplates.7e7539f2-369c-417c-a7ab-9f175208bf0c";
        public const string Name = "WinUI 3 Windows Desktop Templates";
        public const string Description = @"WinUI 3 Windows desktop project and item templates.";
        public const string Language = "en-US";
        public const string Version = "4.4.0.0";
        public const string Author = "Vijay Anand E G";
        public const string Tags = "Blazor, Desktop, WinUI, Windows, Template, BlazorWebView, Hybrid, Razor, Web, GA, .NET MAUI, Client, Modernization, .NET 8, .NET 9, .NET 10, Preview, ARM64, SLNX, WindowsAppSDK, UWP, Win32, WinUI 3, Native Embedding, Library, VS2026, VS2022, Insiders";
    }
}
